# Generated by Django 3.1.5 on 2021-05-02 01:09

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=100)),
                ('Index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Phone_Number', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('Item', models.CharField(max_length=100)),
                ('Price_Organic', models.IntegerField()),
                ('Price_Inorganic', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('City', models.CharField(max_length=100)),
                ('PinCode', models.IntegerField()),
                ('Organic_Inorganic', models.IntegerField()),
                ('Rating', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Availability', models.IntegerField()),
                ('Target', models.IntegerField()),
                ('UserName', models.CharField(max_length=100)),
                ('Password', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FinalUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GivenUserNum', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('Phone_Number', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('Item', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Organic_Inorganic', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Availability', models.IntegerField()),
                ('PinCode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ForgetPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GivenUserNum', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Password', models.IntegerField()),
                ('ConformPassword', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GetDetailsLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GivenUserNum', models.IntegerField()),
                ('UserName', models.CharField(max_length=100)),
                ('Password', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=100)),
                ('Index', models.IntegerField()),
                ('OP', models.IntegerField()),
                ('IP', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RegisterFarmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=100)),
                ('Password', models.IntegerField()),
                ('ConformPassword', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('Phone_Number', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('Item', models.CharField(max_length=100)),
                ('Organic_Inorganic', models.IntegerField()),
                ('City', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('Availability', models.IntegerField()),
                ('PinCode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SerachingFarmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Town', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('Item', models.CharField(max_length=100)),
                ('PinCode', models.IntegerField()),
            ],
        ),
    ]
