# Generated by Django 3.1.5 on 2021-05-02 18:02

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=100)),
                ('Index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Phone_Number', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('City', models.CharField(max_length=100)),
                ('Pin_Code', models.IntegerField()),
                ('Acres', models.IntegerField()),
                ('Rent', models.IntegerField()),
                ('Share', models.IntegerField()),
                ('R_or_S', models.IntegerField()),
                ('Availability', models.IntegerField()),
                ('Target', models.IntegerField()),
                ('UserName', models.CharField(max_length=100)),
                ('Password', models.IntegerField()),
            ],
        ),
    ]
