# Generated by Django 3.1.5 on 2021-05-06 00:06

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('feature1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GivenUserNum', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('Phone_Number', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('City', models.CharField(max_length=100)),
                ('PinCode', models.IntegerField()),
                ('Acres', models.IntegerField()),
                ('Rent', models.IntegerField()),
                ('Share', models.IntegerField()),
                ('R_or_S', models.IntegerField()),
                ('Availability', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ForgetPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GivenUserNum', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Password', models.IntegerField()),
                ('ConformPassword', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GetDetailsLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GivenUserNum', models.IntegerField()),
                ('UserName', models.CharField(max_length=100)),
                ('Password', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RegisterLand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=100)),
                ('Password', models.IntegerField()),
                ('ConformPassword', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('Phone_Number', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('City', models.CharField(max_length=100)),
                ('PinCode', models.IntegerField()),
                ('Acres', models.IntegerField()),
                ('Rent', models.IntegerField()),
                ('Share', models.IntegerField()),
                ('R_or_S', models.IntegerField()),
                ('Availability', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SerachingLand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Town', models.CharField(max_length=100)),
                ('Acres', models.IntegerField()),
                ('PinCode', models.IntegerField()),
            ],
        ),
    ]
